openapi: 3.0.0
info:
  title: "Product API"
  version: "0.1"
servers:
  - url: "http://localhost/api"
paths:
  /product:
    post:
      tags:
        - Product
      operationId: 'App\Http\Controllers\ProductController::store'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                name:
                  description: "Product name"
                  type: string
                sku:
                  description: "Product sku"
                  type: string
                description:
                  description: "Product description"
                  type: string
                price:
                  description: "Product price"
                  type: number
                  format: float
                quantity:
                  description: "Product quantity"
                  type: integer
                  format: int32
              type: object
      responses:
        "201":
          description: "Product created"
          content:
            application/json:
              schema:
                type: null
          #content:
          #  application/json:
          #    schema:
          #      $ref: "#/components/schemas/UserResource"
        #default:
        #  description: "An error occured"
        #  content:
        #    application/json:
        #      schema:
        #        properties:
        #          status:
        #            {
        #              description: "The response status",
        #              type: integer,
        #              format: int64,
        #            }
        #          title:
        #            {
        #              description: "The response not detailed message",
        #              type: string,
        #            }
        #        type: object
#components:
#  schemas:
#    UserResource:
#      properties:
#        id:
#          description: 'The user id'
#          type: string
#        name:
#          description: 'The user name'
#          type: string
#      type: object
